### ISSUE TITLE
Document use of one click with Google Chome, etc (Application cannot be started. Contact the application vendor Error)

### ISSUE THREAD

**Issue by ddieppa** [Microsoft/windows-dev-box-setup-scripts#31]
I was trying to use the **_Web (VS Code, WSL, Multiple Browsers)_**, and I got this error:
```
PLATFORM VERSION INFO
	Windows 			: 10.0.17115.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.7.3053.0 built by: NET472REL1
	clr.dll 			: 4.7.3053.0 built by: NET472REL1
	dfdll.dll 			: 4.7.3053.0 built by: NET472REL1
	dfshim.dll 			: 10.0.17115.1 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///C:/Users/test01/Downloads/Boxstarter.WebLaunch.application

IDENTITIES
	Deployment Identity		: Boxstarter.WebLaunch.application, Version=2.9.27.0, Culture=neutral, PublicKeyToken=6b092740f7261cd0, processorArchitecture=msil

APPLICATION SUMMARY
	* Online only application.
	* Trust url parameter is set.
ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\test01\Downloads\Boxstarter.WebLaunch.application resulted in exception. Following failure messages were detected:
		+ Deployment and application do not have matching security zones.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [5/9/2018 7:42:20 AM] : Activation of C:\Users\test01\Downloads\Boxstarter.WebLaunch.application has started.
	* [5/9/2018 7:42:20 AM] : Processing of deployment manifest has successfully completed.
	* [5/9/2018 7:42:20 AM] : Installation of the application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [5/9/2018 7:42:20 AM] System.Deployment.Application.InvalidDeploymentException (Zone)
		- Deployment and application do not have matching security zones.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.
```

this is my Windows 10 version

![image](https://user-images.githubusercontent.com/10607192/39813351-169336c0-535e-11e8-9b1a-66af45eb8add.png)

And this is my Hyper-V version

![image](https://user-images.githubusercontent.com/10607192/39813375-3768296e-535e-11e8-91e3-b184ee1f0f17.png)

Any Ideas?

**Comment by ddieppa** [comment]
I realize that if I click on the script from **IE** it works, not if you try to do it from **Chrome**.

**Comment by gep13** [comment]
@ddieppa ah, that is a good point.  Perhaps we need to add a mention of that in the readme.  There are some extensions that used to allow ClickOnce to work in Chrome, but I haven't played with any of them recently.

**Comment by ddieppa** [comment]
@gep13 yes, I think to add that part to the readme will be a quick solution to this. Anyways, there is no other solution that can be accomplish within the same boxstarter script?

**Comment by gep13** [comment]
No, not within the Boxstarter Script itself.  This error is occurring before the script is invoked, so there is nothing that can be done from a Boxstarter side of things.

**Comment by yodurr** [comment]
Am adding a comment about this in the Readme's known issues
